import type { Metadata } from 'next';
//@ts-ignore
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import { UserRecordDataProvider } from '@/context/UserRecordDataContext';
import Navbar from '@/components/navbar';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'SwiftDNS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <AuthProvider>
          <UserRecordDataProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <div className="relative h-full bg-background">
                {/* Gradient overlay */}
                <div className="absolute inset-0 bg-background/80">
                  <div className="absolute inset-0 bg-gradient-to-tr from-primary/20 to-secondary/20 blur-3xl" />
                </div>
                <Navbar />
                <div className="py-2 md:py-0">{children}</div>
              </div>
            </ThemeProvider>
          </UserRecordDataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
